#!/usr/bin/env bash
# Show the FORMAT of an OpenSpec artifact using the newest ARCHIVED change as a LIVE, non-rotting
# example — so an agent can see the exact shape before running the openspec-* skills, WITHOUT a static
# template that would rot or tempt hand-writing. READ-ONLY: prints only, creates nothing.
#
# OpenSpec artifacts are OWNED + generated by the openspec-* skills (openspec-propose, openspec validate,
# …). Use this to LEARN the format; never copy it as the artifact — run the skill (complement, don't override).
#
# RUN:  bash .memory/tools/scripts/openspec_example.sh proposal|design|tasks|spec|validation [change-name]
#       (change-name optional; defaults to the newest archived change)
set -uo pipefail
cd "$(git rev-parse --show-toplevel)"
ART="${1:-proposal}"; CH="${2:-}"
BASE="openspec/changes/archive"
[ -n "$CH" ] || CH="$(ls -1 "$BASE" 2>/dev/null | tail -1)"
DIR="$BASE/$CH"
[ -d "$DIR" ] || { echo "no archived change found ($DIR). Available:"; ls -1 "$BASE" 2>/dev/null; exit 1; }
echo "### Example '$ART' from archived change: $CH  (READ-ONLY reference)"; echo
case "$ART" in
  proposal|design|tasks|validation)
    f="$DIR/$ART.md"; if [ -f "$f" ]; then cat "$f"; else echo "(no $ART.md in $CH)"; fi;;
  spec)
    find "$DIR/specs" -name "spec.md" 2>/dev/null | while read -r s; do echo "----- $s -----"; cat "$s"; echo; done;;
  *) echo "usage: openspec_example.sh proposal|design|tasks|spec|validation [change-name]"; exit 2;;
esac
echo; echo ">> REFERENCE ONLY — create/update artifacts via the openspec-* skills, never by copying this."
