environment: abn

statefulset:
  # Number of replicas to run for the statefulset.
  replicas: 3

container:
  # Resource requests and limits for the container.
  resources:
    # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
    limits:
      cpu: 2000m # 2 phusical or virtual cores
      memory: 2000Mi # 2 Gigabytes
    requests:
      cpu: 1000m
      memory: 1000Mi

managedIdentity:
  # Client ID of the managed identity used to authenticate to azure resources.
  # For demo purposes this is a static value, in a real world scenario the recommendation is to
  # deploy the identity with an azure resource deployment and pass the client id as a parameter to helm.
  clientId: '{MANAGED-IDENTITY-CLIENT-ID}'  # Client ID of the managed identity for abn environment

# Azure Key Vault name
keyvaultName: '{project-name}-key-vault-abn'

# Typesense nodes for high availability
nodes: "typesense-0.ts.typesense.svc.cluster.local:8107:8108,typesense-1.ts.typesense.svc.cluster.local:8107:8108,typesense-2.ts.typesense.svc.cluster.local:8107:8108"