parameters:
  - name: deploymentServiceConnection
    type: string

  - name: environment
    type: string

  - name: stageName
    type: string

  - name: kubernetesCluster
    type: string

  - name: kubernetesClusterIssuerUrl
    type: string

  - name: kubernetesClusterResourceGroup
    type: string

  - name: kubernetesClusterSubscription
    type: string

  - name: kubernetesNamespace
    type: string

  - name: resourceGroup
    type: string

  - name: subscriptionName
    type: string

  - name: credentialSeekers
    type: object
    default: []

  - name: previousStageName
    type: string
    default: ""

  - name: managedIdentityName
    type: string
    default: ""

jobs:
  - deployment: create_federated_credentials
    displayName: Create Federated Credentials for Managed Identity
    condition: succeeded()
    environment: ${{ parameters.environment }}
    ${{ if ne( parameters.previousStageName, '' ) }}:
      dependsOn:
        - ${{ parameters.previousStageName }}
    variables:
      ${{ if eq( parameters.managedIdentityName, '' ) }}:
        managedIdentityName: $[dependencies.deploy_azure_infrastructure.outputs['deploy_azure_infrastructure.infrastructureDeploymentOutputParameters.managedIdentityName']]
      ${{ else }}:
        managedIdentityName: ${{ parameters.managedIdentityName }}
    strategy:
      runOnce:
        # https://learn.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#descriptions-of-lifecycle-hooks
        deploy:
          steps:
            - checkout: none
            - download: none

            - script: |
                echo "##[debug] Parameters:"
                echo "##[debug] Deployment Service Connection: ${{ parameters.deploymentServiceConnection }}"
                echo "##[debug] Environment: ${{ parameters.environment }}"
                echo "##[debug] Kubernetes Cluster Issuer Url: ${{ parameters.kubernetesClusterIssuerUrl }}"
                echo "##[debug] Kubernetes Cluster Resource Group: ${{ parameters.kubernetesClusterResourceGroup }}"
                echo "##[debug] Kubernetes Cluster Subscription: ${{ parameters.kubernetesClusterSubscription }}"
                echo "##[debug] Kubernetes Cluster: ${{ parameters.kubernetesCluster }}"
                echo "##[debug] Kubernetes Namespace: ${{ parameters.kubernetesNamespace }}"
                echo "##[debug] Managed Identity Name: $(managedIdentityName)"
                echo "##[debug] Resource Group: ${{ parameters.resourceGroup }}"
                echo "##[debug] Stage Name: ${{ parameters.stageName }}"
                echo "##[debug] Subscription Name: ${{ parameters.subscriptionName }}"
              displayName: "Prep: Create Federated Credentials for Managed Identity"

            - ${{ each seeker in parameters.credentialSeekers }}:
                - task: AzureCLI@2
                  displayName: Create Federated Credentials for Managed Identity
                  inputs:
                    azureSubscription: ${{ parameters.deploymentServiceConnection }}
                    scriptType: bash
                    scriptLocation: inlineScript
                    addSpnToEnvironment: true
                    inlineScript: |
                      managedIdentityName="$(managedIdentityName)"
                      kubernetesServiceAccount="${{ seeker.serviceAccount }}"
                      resourceGroup="${{ parameters.resourceGroup }}"
                      kubernetesClusterIssuerUrl="${{ parameters.kubernetesClusterIssuerUrl }}"
                      kubernetesNamespace="${{ seeker.namespace }}"
                      subject="system:serviceaccount:$kubernetesNamespace:$kubernetesServiceAccount"

                      echo "Managed Identity Name: $managedIdentityName"
                      echo "Kubernetes Service Account: $kubernetesServiceAccount"
                      echo "Resource Group: $resourceGroup"
                      echo "Kubernetes Issuer Url: $kubernetesClusterIssuerUrl"
                      echo "Kubernetes Namespace: $kubernetesNamespace"
                      echo "Subject: $subject"

                      az identity federated-credential create --identity-name "$managedIdentityName" --name "$kubernetesServiceAccount" --resource-group "$resourceGroup" --issuer "$kubernetesClusterIssuerUrl" --subject "$subject" --debug
