parameters:
  - name: artifactName
    type: string

  - name: deploymentServiceConnection
    type: string

  - name: stageName
    type: string

  - name: environment
    type: string

  # Specifies the helm version to install on the agent.
  - name: helmVersionToInstall
    type: string
    default: latest

  - name: helmChartName
    type: string

  - name: acrName
    type: string

  - name: kubernetesCluster
    type: string

  - name: kubernetesClusterResourceGroup
    type: string

  - name: kubernetesClusterSubscription
    type: string

  - name: kubernetesNamespace
    type: string

  - name: kubernetesTenant
    type: string

  - name: acrServiceConnection
    type: string

  - name: apiBaseUrl
    type: string

  - name: dockerFrontendImageName
    type: string

  - name: dockerImageTag
    type: string

  - name: containerRegistryDomain
    type: string
    default: azurecr.io

  - name: variableGroup
    type: string

jobs:
  - deployment: deploy_app_to_kubernetes
    displayName: Deploy App to Kubernetes
    condition: eq(variables['uiChanged'], true)
    environment: ${{ parameters.environment }}
    dependsOn:
      - create_federated_credentials
      - deploy_azure_infrastructure
    variables:
      - group: ${{ parameters.variableGroup }}
      - name: managedIdentityClientId
        value: $[dependencies.deploy_azure_infrastructure.outputs['deploy_azure_infrastructure.infrastructureDeploymentOutputParameters.managedIdentityClientId']]
    strategy:
      runOnce:
        # https://learn.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops#descriptions-of-lifecycle-hooks
        deploy:
          steps:
            - checkout: self

            - download: current
              artifact: ${{ parameters.artifactName }}
              displayName: Download Helm Chart Artifacts

            - script: |
                echo "##[debug] Parameters:"
                echo "##[debug] ACR Name: ${{ parameters.acrName }}"
                echo "##[debug] ACR Service Connection: ${{ parameters.acrServiceConnection }}"
                echo "##[debug] API Base URL: $(NEXT_PUBLIC_API_BASE_URL)"
                echo "##[debug] Deployment Service Connection: ${{ parameters.deploymentServiceConnection }}"
                echo "##[debug] Environment: ${{ parameters.environment }}"
                echo "##[debug] Helm Version to Install: ${{ parameters.helmVersionToInstall }}"
                echo "##[debug] Kubernetes Cluster Resource Group: ${{ parameters.kubernetesClusterResourceGroup }}"
                echo "##[debug] Kubernetes Cluster Subscription: ${{ parameters.kubernetesClusterSubscription }}"
                echo "##[debug] Kubernetes Cluster: ${{ parameters.kubernetesCluster }}"
                echo "##[debug] Kubernetes Namespace: ${{ parameters.kubernetesNamespace }}"
                echo "##[debug] Stage Name: ${{ parameters.stageName }}"
                echo "##[debug] Variable Group: ${{ parameters.variableGroup }}"
              displayName: "Prep: Deploy API to Kubernetes"

            # Replace tokens in the environment files before deployment.
            - task: qetza.replacetokens.replacetokens-task.replacetokens@6
              displayName: Replace Tokens in Configuration Files
              inputs:
                logLevel: debug
                missingVarAction: keep
                missingVarLog: warn
                sources: 'src/frontend/.env.production'
                telemetryOptout: false
                tokenPattern: custom
                tokenPrefix: '#{'
                tokenSuffix: '}#'

            # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2
            - task: AzureCLI@2
              name: acrLogin
              displayName: Login to ACR
              inputs:
                azureSubscription: ${{ parameters.acrServiceConnection }}
                scriptType: pscore
                scriptLocation: inlineScript
                inlineScript: |
                  az acr login -n ${{ parameters.acrName }}
                  $loginServer = "${{ parameters.acrName }}.${{ parameters.containerRegistryDomain }}"
                  echo "##[debug] Login server: '$loginServer'"
                  Write-Host "##vso[task.setvariable variable=containerRegistryLoginServer;issecret=true]$loginServer"

            - template: job-build-push-docker-image.yml
              parameters:
                acrServiceConnection: ${{ parameters.acrServiceConnection }}
                dockerBuildArgs: --build-arg PAT=$(System.AccessToken)
                dockerContextPath: $(Build.SourcesDirectory)/src/frontend
                dockerfilePath: $(Build.SourcesDirectory)/src/frontend/Dockerfile
                dockerImageName: ${{ parameters.dockerFrontendImageName }}
                dockerImageTag: ${{ parameters.dockerImageTag }}

            - task: HelmInstaller@1
              displayName: Helm Installer
              inputs:
                helmVersionToInstall: ${{ parameters.helmVersionToInstall }}
                installKubectl: false

            # Log in to the Kubernetes cluster.
            - template: job-kubernetes-login.yml
              parameters:
                kubernetesCluster: ${{ parameters.kubernetesCluster }}
                kubernetesClusterResourceGroup: ${{ parameters.kubernetesClusterResourceGroup }}
                kubernetesClusterSubscription: ${{ parameters.kubernetesClusterSubscription }}
                deploymentServiceConnection: ${{ parameters.deploymentServiceConnection }}

            # Helm can run into issues if the namespace is not created when installing the application, so it's safer to create it before the deployment.
            - task: AzureCLI@2
              displayName: Create Namespace
              inputs:
                azureSubscription: ${{ parameters.deploymentServiceConnection }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  kubectl create namespace "${{ parameters.kubernetesNamespace }}" --dry-run=client -o yaml | kubectl apply -f -

            # Install the application using helm.
            # We provide two values files, one for the global, and one for the stage specific values
            # if a property is in both value files, the last value file provided to the helm command takes prcedence
            # We can also provide runtime parameters using --set. This can be done multiple times.
            - task: AzureCLI@2
              displayName: Deploy Helm Chart
              retryCountOnTaskFailure: 3
              inputs:
                azureSubscription: ${{ parameters.deploymentServiceConnection }}
                scriptType: bash
                scriptLocation: inlineScript
                addSpnToEnvironment: true
                inlineScript: |
                  # set -x is used to print the commands before they are executed, which is very useful for debugging.
                  set -x

                  helm upgrade ${{ parameters.helmChartName }} \
                    oci://${{ parameters.acrName }}.azurecr.io/${{ parameters.kubernetesTenant }}/helm/${{ parameters.helmChartName }} \
                    --version=$(Build.BuildNumber) \
                    --values "$(Agent.BuildDirectory)/${{ parameters.artifactName }}/values.yaml" \
                    --values "$(Agent.BuildDirectory)/${{ parameters.artifactName }}/values-${{ parameters.stageName }}.yaml" \
                    --install \
                    --namespace ${{ parameters.kubernetesNamespace }} \
                    --set container.imageVersion="$(Build.SourceVersion)" \
                    --set managedIdentity.clientId="$(managedIdentityClientId)" \
                    --timeout 10m00s \
                    --wait
