apiVersion: v2
name: {project-name}-api  # Replace {project-name} with your actual project name
description: Helm chart for {PROJECT-NAME} API
maintainers:
- name: {team-name}
version: 1.0.0
appVersion: "1.0.0"
