apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: additional-access
rules:
# Run rollout restart
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch"]
# Restart Pods manually
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "get", "list", "watch"]
# Troubleshooting within the container
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
# Create port-forward
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
# List secrets
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: additional-access-binding
subjects:
- kind: User
  name: "{USER-PRINCIPAL-NAME-1}@{client-name}.onmicrosoft.com" # User principal name — replace with your team member's UPN
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: "{USER-PRINCIPAL-NAME-2}@{client-name}.onmicrosoft.com" # User principal name — replace with your team member's UPN
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: additional-access
  apiGroup: rbac.authorization.k8s.io