apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "release.fullname" . }}-spc
spec:
  provider: azure
  parameters:
    clientID: {{ .Values.managedIdentity.clientId }}
    keyvaultName: {{ .Values.keyvaultName }}
    tenantId: {{ .Values.tenantId }}
    objects: |
      array:
        - |
          objectName: Typesense--ApiKey
          objectType: secret
  secretObjects:
  - secretName: typesense-secrets
    type: Opaque
    data:
      - objectName: Typesense--ApiKey
        key: Typesense--ApiKey