apiVersion: v1
kind: Service
metadata:
  name: {{ include "release.fullname" . }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "release.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
  selector:
    app: {{ include "release.fullname" . }}