apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "release.fullname" . }}-sa
  annotations:
    # Client ID of the managed identity mapped to the service account
    azure.workload.identity/client-id: {{ .Values.managedIdentity.clientId }}