## please make sure the build context is the directory where this Dockerfile is located
# syntax=docker/dockerfile:1.4
FROM node:18.19.1-alpine AS base

# Disable telemetry at the base stage.
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm set strict-ssl false
RUN npm install -g pnpm@8.9.2

# Install dependencies only when needed
FROM base AS deps
ARG PAT

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
#RUN apk add --no-cache libc6-compat

WORKDIR /app

# Install dependencies
COPY package.json pnpm-lock.yaml ./

## create .npmrc file with npm credentials with auth
## Replace {AZURE-DEVOPS-ORG}, {FEED-NAME}, and {client-domain} with your project-specific values
RUN echo "registry=http://pkgs.dev.azure.com/{AZURE-DEVOPS-ORG}/_packaging/{FEED-NAME}/npm/registry/" >> .npmrc && \
  echo "//pkgs.dev.azure.com/{AZURE-DEVOPS-ORG}/_packaging/{FEED-NAME}/npm/registry/:_authToken=$PAT" >> .npmrc && \
  echo "//pkgs.dev.azure.com/{AZURE-DEVOPS-ORG}/_packaging/{FEED-NAME}/npm/registry/:email=whatever@{client-domain}" >> .npmrc && \
  echo "//pkgs.dev.azure.com/{AZURE-DEVOPS-ORG}/_packaging/{FEED-NAME}/npm/:_authToken=$PAT" >> .npmrc && \
  echo "//pkgs.dev.azure.com/{AZURE-DEVOPS-ORG}/_packaging/{FEED-NAME}/npm/:email=whatever@{client-domain}" >> .npmrc; \
  echo "always-auth=true" >> .npmrc

RUN pnpm install

RUN rm -rf .npmrc

# # Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
COPY .env.docker .env.local
# keep only .env.production
#RUN rm -rf .env.development .env.test

RUN pnpm build

RUN rm -rf .npmrc

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=development

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000
# Set hostname to localhost
ENV HOSTNAME="0.0.0.0"

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD ["node", "server.js"]